"use client";

import {
  VehicleSheet,
  type ColDef,
  type FilterField,
} from "@/components/vehicles/vehicle-sheet";

// v4.1 spec §11.9: Master Sheet column order — row counter is column 1
// (auto-generated by the sheet), then Stock ID is column 2 as its own column
// (Bass Bhai feedback v4.1), then Vehicle (reg + image), then the rest.
const COLS: ColDef[] = [
  { key: "stockId", label: "Stock ID", type: "stockId", width: 100, sticky: true },
  { key: "stockId", label: "Vehicle", type: "vehicle", width: 170 },
  { key: "make", label: "Make", type: "select", width: 110 },
  { key: "model", label: "Model", type: "text", width: 130 },
  { key: "variantCode", label: "Variant", type: "text", width: 220 },
  { key: "year", label: "Year", type: "number", width: 70 },
  { key: "colour", label: "Colour", type: "select", width: 100 },
  { key: "mileage", label: "Mileage", type: "number", width: 90 },
  { key: "vehicleType", label: "Type", type: "select", width: 80 },
  { key: "bodyType", label: "Body", type: "select", width: 110 },
  { key: "fuelType", label: "Fuel", type: "select", width: 90 },
  { key: "transmission", label: "Trans", type: "select", width: 110 },
  { key: "engineSizeCC", label: "Engine cc", type: "number", width: 90 },
  { key: "receivedDate", label: "Received", type: "date", width: 120 },
  { key: "sellerName", label: "Seller", type: "text", width: 140 },
  { key: "sellerPhone", label: "Phone", type: "text", width: 120 },
  { key: "purchaseSource", label: "Purchase Source", type: "select", width: 130 },
  { key: "auctionHouse", label: "Auction", type: "text", width: 130 },
  { key: "v5Received", label: "V5", type: "boolean", width: 60 },
  { key: "serviceHistory", label: "SH", type: "select", width: 90 },
  { key: "numKeys", label: "Keys", type: "number", width: 60 },
  { key: "lockNut", label: "Lock", type: "boolean", width: 60 },
  { key: "motExpiry", label: "MOT", type: "date", width: 120 },
  { key: "buyingPrice", label: "Buying", type: "currency", width: 110 },
  { key: "buyersFee", label: "Buyer fee", type: "currency", width: 100 },
  { key: "collectionFee", label: "Coll. fee", type: "currency", width: 100 },
  { key: "totalBuyingPrice", label: "Total buying", type: "currency", width: 120 },
  { key: "financeProvider", label: "Finance", type: "select", width: 130 },
  { key: "stockingCharges", label: "Stocking", type: "currency", width: 110 },
  { key: "valueAddition", label: "Value add", type: "currency", width: 110 },
  { key: "warrantyCost", label: "Warranty", type: "currency", width: 110 },
  { key: "landedCost", label: "Landed", type: "currency", width: 110 },
  { key: "baseCost", label: "Base cost", type: "currency", width: 110 },
  { key: "minimumSalePrice", label: "Min sale", type: "currency", width: 110 },
  { key: "listingPrice", label: "Listing", type: "currency", width: 110 },
  { key: "sellingPrice", label: "Sold", type: "currency", width: 110 },
  { key: "dateSold", label: "Sold date", type: "date", width: 120 },
  { key: "sellingAgent", label: "Agent", type: "text", width: 130 },
  { key: "grossEarning", label: "Gross", type: "currency", width: 110 },
  // Est. profit is derived centrally in vehicle-sheet (rawValue) so the
  // on-screen cell and the CSV export share one source of truth.
  { key: "profit", label: "Est. profit", type: "currency", width: 110 },
  { key: "status", label: "Status", type: "status", width: 140 },
  // Spec v3.0 · Module A — Location with Off-site badge for Garage/Staff.
  { key: "currentLocation", label: "Location", type: "location", width: 150 },
  { key: "daysInStock", label: "Days", type: "number", width: 70 },
  { key: "imagesCount", label: "Imgs", type: "number", width: 70 },
];

const FILTER_FIELDS: FilterField[] = [
  { key: "make", label: "Make", kind: "text" },
  { key: "model", label: "Model", kind: "text" },
  { key: "year", label: "Year", kind: "num" },
  { key: "colour", label: "Colour", kind: "text" },
  { key: "mileage", label: "Mileage", kind: "num" },
  { key: "vehicleType", label: "Type", kind: "text" },
  { key: "bodyType", label: "Body", kind: "text" },
  { key: "fuelType", label: "Fuel", kind: "text" },
  { key: "transmission", label: "Transmission", kind: "text" },
  { key: "status", label: "Status", kind: "text" },
  { key: "listingPrice", label: "Listing price", kind: "num" },
  { key: "daysInStock", label: "Days in stock", kind: "num" },
];

export default function MasterSheetPage() {
  return (
    <VehicleSheet
      title="Master Sheet"
      cols={COLS}
      filterFields={FILTER_FIELDS}
      csvName="master-sheet"
      summary={(count, selected) =>
        `The complete record of every vehicle, with all fields in one wide grid. ${
          count ?? "—"
        } row${count === 1 ? "" : "s"}${
          selected > 0 ? ` · ${selected} selected` : ""
        }.`
      }
    />
  );
}
